package br.com.view;

import br.com.controller.CidadeController;
import br.com.model.negosio.Cidade;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author clayson_medeiros
 */
public class InserirCidadeGUI extends javax.swing.JFrame {

    CidadeTableModel model;

    /**
     * Creates new form InserirAutomovelGui
     */
    public InserirCidadeGUI(CidadeTableModel mtb) {
        initComponents();
        model = mtb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botaoLimpar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        lbNome = new javax.swing.JLabel();
        lbUf = new javax.swing.JLabel();
        txUf = new javax.swing.JTextField();
        txNome = new javax.swing.JTextField();

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("YYYY"))));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Marca");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("Inserir Automóvel");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 85, 14);

        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });
        jPanel1.add(botaoLimpar);
        botaoLimpar.setBounds(20, 150, 90, 23);

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoSalvar);
        botaoSalvar.setBounds(120, 150, 70, 23);

        lbNome.setText("Nome:");
        jPanel1.add(lbNome);
        lbNome.setBounds(10, 40, 40, 14);

        lbUf.setText("UF:");
        jPanel1.add(lbUf);
        lbUf.setBounds(10, 70, 20, 14);
        jPanel1.add(txUf);
        txUf.setBounds(110, 70, 70, 20);
        jPanel1.add(txNome);
        txNome.setBounds(110, 40, 70, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
           Cidade cidade = new Cidade();           
           cidade.setUf((txUf.getText()));          
           cidade.setNome((txNome.getText()));           
           CidadeController cc = new CidadeController();
           cc.salvar(cidade);           
           dispose();        
    }//GEN-LAST:event_botaoSalvarActionPerformed

  
    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        txUf.setText(" ");
        txNome.setText("");       
    }//GEN-LAST:event_botaoLimparActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbUf;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txUf;
    // End of variables declaration//GEN-END:variables
}
